#!/bin/bash 


### Wrapper script for launching snakemake workflow ### 
clear
echo "Launching snakemake workflow..."
sleep 3
echo "Beginning executing on: $(date)"

source activate snakemake 

### Run bracken and humann3 rules prior to a full run - to ensure rules for utility scripts run correctly 
snakemake --profile slurm -R brackenSpecies brackenGenus humann3Uniref50EC

snakemake --profile slurm

snakemake --report snakemakeReport.html

snakemake --rulegraph | dot -T svg > rulegraph.svg

conda deactivate 

echo "Snakemake run completed: $(date)"